<a href="https://colab.research.google.com/github/samridhi25445/ChatGPT-Analysis/blob/main/ChatGPT_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
# Importing important libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk as nltk

In [6]:
# Importing the dataset
df = pd.read_csv('/chatgpt_reviews.csv')
df.head()

,Review Id,Review,Ratings,Review Date
0,6fb93778-651a-4ad1-b5ed-67dd0bd35aac,good,5,2024-08-23 19:30:05
1,81caeefd-3a28-4601-a898-72897ac906f5,good,5,2024-08-23 19:28:18
2,452af49e-1d8b-4b68-b1ac-a94c64cb1dd5,nice app,5,2024-08-23 19:22:59
3,372a4096-ee6a-4b94-b046-cef0b646c965,"nice, ig",5,2024-08-23 19:20:50
4,b0d66a4b-9bde-4b7c-8b11-66ed6ccdd7da,"this is a great app, the bot is so accurate to...",5,2024-08-23 19:20:39

In [9]:
# Getting an idea abput duplicate rows
df.duplicated().sum()

np.int64(2511)

In [10]:
#np.int64(2511) means that there are 2511 rows in the dataset.

In [14]:
# Dropping the duplicate data
df = df.drop_duplicates()

# Getting an idea about duplicate rows
df.duplicated().sum()

np.int64(0)

In [15]:
#np.int64(0) means that there are 0 rows in the dataset.

In [16]:
# Getting an idea about null values
df.isnull().sum().any()

np.True_

In [ ]:
# np.True_ means that there are NULL values in the dataset

In [17]:
#Getting an idea about the column wise sum of NULL values
df.isnull().sum()

Review Id      0
Review         6
Ratings        0
Review Date    0
dtype: int64

In [18]:
# Getting an idea about the shape of the dataset
print('Shape :', df.shape)
print('Number of rows :', df.shape[0])
print('Number of columns :', df.shape[1])

Shape : (194216, 4)
Number of rows : 194216
Number of columns : 4

In [21]:
# Dropping the rows with the NULL values
df=df.dropna()

# Checking the NULL Values in the dataset
df.isnull().sum() #gives the columns with null values
df.isnull().sum().any() #give True or False

np.False_

In [22]:
# Getting an idea of data types of the columns
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 194210 entries, 0 to 196726
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Review Id    194210 non-null  object
 1   Review       194210 non-null  object
 2   Ratings      194210 non-null  int64
 3   Review Date  194210 non-null  object
dtypes: int64(1), object(3)
memory usage: 7.4+ MB

In [23]:
# Converting the 'Review Date' column to datetime format
df['Review Date'] = pd.to_datetime(df['Review Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 194210 entries, 0 to 196726
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Review Id    194210 non-null  object
 1   Review       194210 non-null  object
 2   Ratings      194210 non-null  int64
 3   Review Date  194210 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 7.4+ MB

In [24]:
# Getting an idea abput the range of values in 'Ratings'
print('Manimum Value :',df['Ratings'].min())
print('Maximum Value :',df['Ratings'].max())

Manimum Value : 1
Maximum Value : 5